In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.5.0


In [3]:
import tensorflow as tf

devices = tf.config.list_physical_devices()
for device in devices:
    print(device)


PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')
PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')


In [4]:
import tensorflow as tf
print("GPU Available: ", len(tf.config.list_physical_devices('GPU')) > 0)


GPU Available:  True


###################


In [5]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.13002172, -0.40565985,  0.46899658,  0.0453722 ,  0.34314114,
         0.07448871,  0.18015474, -0.18021284,  0.15032054, -0.16396043]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.10371715, 0.06070256, 0.14556785, 0.09529886, 0.12835333,
        0.09811442, 0.10904934, 0.07605319, 0.10584399, 0.07729934]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

2.321621

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 6s 2ms/step - loss: 0.2962 - accuracy: 0.9131
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1430 - accuracy: 0.9571
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1069 - accuracy: 0.9667
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0845 - accuracy: 0.9736
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0743 - accuracy: 0.9765
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0629 - accuracy: 0.9801
Epoch 7/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0571 - accuracy: 0.9807
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0498 - accuracy: 0.9841
Epoch 9/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0473 - accuracy: 0.9844
Epoch 10/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.039

In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0692 - accuracy: 0.9811


[0.0692119151353836, 0.9811000227928162]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.26768260e-10, 9.37549487e-08, 1.19305787e-06, 9.82854108e-05,
        1.08571345e-14, 2.38116353e-08, 2.02774989e-17, 9.99900341e-01,
        6.50283027e-08, 5.10215408e-08],
       [5.46523049e-10, 2.14186826e-07, 9.99999523e-01, 2.01823724e-07,
        1.09641263e-24, 6.73692124e-09, 2.94330976e-10, 6.99604030e-19,
        2.28153141e-09, 1.69633171e-16],
       [8.87835583e-09, 9.99832630e-01, 9.80825553e-06, 1.00318353e-07,
        3.19937099e-05, 1.44075102e-07, 7.43856788e-07, 7.46102669e-05,
        4.99520938e-05, 4.06372429e-08],
       [9.99973655e-01, 1.34699075e-11, 2.03037816e-05, 1.56154889e-09,
        1.76308686e-12, 8.90766557e-07, 5.72585520e-07, 4.88437166e-08,
        4.50453230e-10, 4.51998540e-06],
       [7.40208770e-06, 3.08194876e-12, 9.38731682e-06, 1.24511179e-10,
        9.49373901e-01, 2.63227697e-08, 2.22278828e-07, 2.00324546e-04,
        2.09777795e-08, 5.04087508e-02]], dtype=float32)>