In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.5.0


In [2]:
import tensorflow as tf

devices = tf.config.list_physical_devices()
for device in devices:
    print(device)


PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')
PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')


In [3]:
import tensorflow as tf
print("GPU Available: ", len(tf.config.list_physical_devices('GPU')) > 0)


GPU Available:  True


###################


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.24964598, -0.03930372,  0.0107397 ,  0.13255182,  0.49036583,
        -0.24585995, -0.36382225,  0.07543653,  0.14664344, -0.23926003]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.07770146, 0.0958914 , 0.10081223, 0.11387163, 0.16285917,
        0.0779962 , 0.06931753, 0.10755008, 0.11548763, 0.07851266]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

2.5510952

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2958 - accuracy: 0.9143
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1394 - accuracy: 0.9583
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1051 - accuracy: 0.9688
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0871 - accuracy: 0.9729
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0739 - accuracy: 0.9772
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0656 - accuracy: 0.9791
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0572 - accuracy: 0.9812
Epoch 8/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0534 - accuracy: 0.9824
Epoch 9/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0492 - accuracy: 0.9837
Epoch 10/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.044

In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0725 - accuracy: 0.9795


[0.07253263145685196, 0.9794999957084656]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.02075995e-11, 1.32173777e-11, 8.54671089e-09, 3.57981025e-06,
        8.64114372e-16, 6.76306455e-10, 6.64842385e-19, 9.99995589e-01,
        2.10056661e-09, 8.84354733e-07],
       [1.62915459e-10, 1.72357017e-04, 9.99827087e-01, 5.40237124e-07,
        1.23956530e-18, 6.03661743e-09, 4.86313073e-12, 1.28817438e-15,
        1.09844370e-10, 1.67434263e-13],
       [8.31807845e-10, 9.96256709e-01, 5.95925994e-05, 7.07978586e-07,
        1.53216359e-04, 5.63684807e-07, 5.25920882e-07, 3.45192500e-03,
        7.67045713e-05, 7.76011166e-09],
       [9.99992728e-01, 3.07055735e-11, 2.85589499e-06, 3.04925218e-09,
        7.38697825e-10, 2.94048697e-08, 3.91662661e-06, 1.15460779e-08,
        1.80168131e-12, 5.03627859e-07],
       [5.18250154e-08, 2.36539632e-09, 1.82088343e-06, 5.35297895e-09,
        9.94098663e-01, 2.55393857e-08, 2.12634987e-07, 2.88908079e-04,
        6.54062490e-07, 5.60967112e-03]], dtype=float32)>